// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEzZEbHRNJIwmVW1s6N8YbjMgdQ1ntFFw',
    appId: '1:293131990145:web:1f246223373c05d2020980',
    messagingSenderId: '293131990145',
    projectId: 'musteridefterim-c99bf',
    authDomain: 'musteridefterim-c99bf.firebaseapp.com',
    storageBucket: 'musteridefterim-c99bf.firebasestorage.app',
    measurementId: 'G-GG4G7YN17F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_W9fN_tV4mkWag5DmIKhke0AIb94jh8',
    appId: '1:293131990145:android:ca3896410cdcff70020980',
    messagingSenderId: '293131990145',
    projectId: 'musteridefterim-c99bf',
    storageBucket: 'musteridefterim-c99bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRTHXmoTrJMiR_NM7b_LF8oFCfT6K2-Y',
    appId: '1:293131990145:ios:6e386185c78857c9020980',
    messagingSenderId: '293131990145',
    projectId: 'musteridefterim-c99bf',
    storageBucket: 'musteridefterim-c99bf.firebasestorage.app',
    iosBundleId: 'com.example.musteridefterim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRTHXmoTrJMiR_NM7b_LF8oFCfT6K2-Y',
    appId: '1:293131990145:ios:6e386185c78857c9020980',
    messagingSenderId: '293131990145',
    projectId: 'musteridefterim-c99bf',
    storageBucket: 'musteridefterim-c99bf.firebasestorage.app',
    iosBundleId: 'com.example.musteridefterim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEzZEbHRNJIwmVW1s6N8YbjMgdQ1ntFFw',
    appId: '1:293131990145:web:0f4892fef4fdd626020980',
    messagingSenderId: '293131990145',
    projectId: 'musteridefterim-c99bf',
    authDomain: 'musteridefterim-c99bf.firebaseapp.com',
    storageBucket: 'musteridefterim-c99bf.firebasestorage.app',
    measurementId: 'G-5YV643MRSW',
  );

}